//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessibilityInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessibilityInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuditoryImpairment" type="{urn:tva:mpeg21:2012}AuditoryImpairmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="VisualImpairment" type="{urn:tva:mpeg21:2012}VisualImpairmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OtherAccessibilityCharacteristics" type="{urn:tva:metadata:2012}ControlledTermType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessibilityInformationType", namespace = "urn:tva:metadata:extended:2012", propOrder = {
    "auditoryImpairment",
    "visualImpairment",
    "otherAccessibilityCharacteristics"
})
public class AccessibilityInformationType {

    @XmlElement(name = "AuditoryImpairment")
    protected List<AuditoryImpairmentType> auditoryImpairment;
    @XmlElement(name = "VisualImpairment")
    protected List<VisualImpairmentType> visualImpairment;
    @XmlElement(name = "OtherAccessibilityCharacteristics")
    protected List<ControlledTermType> otherAccessibilityCharacteristics;

    /**
     * Gets the value of the auditoryImpairment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auditoryImpairment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuditoryImpairment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuditoryImpairmentType }
     * 
     * 
     */
    public List<AuditoryImpairmentType> getAuditoryImpairment() {
        if (auditoryImpairment == null) {
            auditoryImpairment = new ArrayList<AuditoryImpairmentType>();
        }
        return this.auditoryImpairment;
    }

    /**
     * Gets the value of the visualImpairment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visualImpairment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisualImpairment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VisualImpairmentType }
     * 
     * 
     */
    public List<VisualImpairmentType> getVisualImpairment() {
        if (visualImpairment == null) {
            visualImpairment = new ArrayList<VisualImpairmentType>();
        }
        return this.visualImpairment;
    }

    /**
     * Gets the value of the otherAccessibilityCharacteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherAccessibilityCharacteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherAccessibilityCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlledTermType }
     * 
     * 
     */
    public List<ControlledTermType> getOtherAccessibilityCharacteristics() {
        if (otherAccessibilityCharacteristics == null) {
            otherAccessibilityCharacteristics = new ArrayList<ControlledTermType>();
        }
        return this.otherAccessibilityCharacteristics;
    }

}
