//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuditoryImpairmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditoryImpairmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}UserCharacteristicBaseType">
 *       &lt;sequence>
 *         &lt;element name="RightEar" type="{urn:tva:mpeg21:2012}AudiogramType"/>
 *         &lt;element name="LeftEar" type="{urn:tva:mpeg21:2012}AudiogramType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditoryImpairmentType", propOrder = {
    "rightEar",
    "leftEar"
})
public class AuditoryImpairmentType
    extends UserCharacteristicBaseType
{

    @XmlElement(name = "RightEar", required = true)
    protected AudiogramType rightEar;
    @XmlElement(name = "LeftEar", required = true)
    protected AudiogramType leftEar;

    /**
     * Gets the value of the rightEar property.
     * 
     * @return
     *     possible object is
     *     {@link AudiogramType }
     *     
     */
    public AudiogramType getRightEar() {
        return rightEar;
    }

    /**
     * Sets the value of the rightEar property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudiogramType }
     *     
     */
    public void setRightEar(AudiogramType value) {
        this.rightEar = value;
    }

    /**
     * Gets the value of the leftEar property.
     * 
     * @return
     *     possible object is
     *     {@link AudiogramType }
     *     
     */
    public AudiogramType getLeftEar() {
        return leftEar;
    }

    /**
     * Sets the value of the leftEar property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudiogramType }
     *     
     */
    public void setLeftEar(AudiogramType value) {
        this.leftEar = value;
    }

}
