//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AwardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AwardType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Category" type="{urn:tva:mpeg7:2008}TextualType"/>
 *         &lt;choice minOccurs="0">
 *           &lt;choice>
 *             &lt;element name="Nominee" type="{urn:tva:metadata:2012}CreditsItemType" minOccurs="0"/>
 *             &lt;element name="Recipient" type="{urn:tva:metadata:2012}CreditsItemType" minOccurs="0"/>
 *           &lt;/choice>
 *           &lt;choice>
 *             &lt;element name="Nominated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *             &lt;element name="Awarded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AwardType", namespace = "urn:tva:metadata:2012", propOrder = {
    "category",
    "nominee",
    "recipient",
    "nominated",
    "awarded"
})
public class AwardType {

    @XmlElement(name = "Category", required = true)
    protected TextualType category;
    @XmlElement(name = "Nominee")
    protected CreditsItemType nominee;
    @XmlElement(name = "Recipient")
    protected CreditsItemType recipient;
    @XmlElement(name = "Nominated", defaultValue = "true")
    protected Boolean nominated;
    @XmlElement(name = "Awarded", defaultValue = "true")
    protected Boolean awarded;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link TextualType }
     *     
     */
    public TextualType getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextualType }
     *     
     */
    public void setCategory(TextualType value) {
        this.category = value;
    }

    /**
     * Gets the value of the nominee property.
     * 
     * @return
     *     possible object is
     *     {@link CreditsItemType }
     *     
     */
    public CreditsItemType getNominee() {
        return nominee;
    }

    /**
     * Sets the value of the nominee property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditsItemType }
     *     
     */
    public void setNominee(CreditsItemType value) {
        this.nominee = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link CreditsItemType }
     *     
     */
    public CreditsItemType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditsItemType }
     *     
     */
    public void setRecipient(CreditsItemType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the nominated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNominated() {
        return nominated;
    }

    /**
     * Sets the value of the nominated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNominated(Boolean value) {
        this.nominated = value;
    }

    /**
     * Gets the value of the awarded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAwarded() {
        return awarded;
    }

    /**
     * Sets the value of the awarded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAwarded(Boolean value) {
        this.awarded = value;
    }

}
