//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConversionPreferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConversionPreferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}UserCharacteristicBaseType">
 *       &lt;sequence>
 *         &lt;element name="GeneralResourceConversions" type="{urn:tva:mpeg21:2012}ResourceConversionType" minOccurs="0"/>
 *         &lt;element name="SpecificResourceConversions" type="{urn:tva:mpeg21:2012}SpecificResourceConversionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConversionPreferenceType", propOrder = {
    "generalResourceConversions",
    "specificResourceConversions"
})
public class ConversionPreferenceType
    extends UserCharacteristicBaseType
{

    @XmlElement(name = "GeneralResourceConversions")
    protected ResourceConversionType generalResourceConversions;
    @XmlElement(name = "SpecificResourceConversions")
    protected SpecificResourceConversionsType specificResourceConversions;

    /**
     * Gets the value of the generalResourceConversions property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceConversionType }
     *     
     */
    public ResourceConversionType getGeneralResourceConversions() {
        return generalResourceConversions;
    }

    /**
     * Sets the value of the generalResourceConversions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceConversionType }
     *     
     */
    public void setGeneralResourceConversions(ResourceConversionType value) {
        this.generalResourceConversions = value;
    }

    /**
     * Gets the value of the specificResourceConversions property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificResourceConversionsType }
     *     
     */
    public SpecificResourceConversionsType getSpecificResourceConversions() {
        return specificResourceConversions;
    }

    /**
     * Sets the value of the specificResourceConversions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificResourceConversionsType }
     *     
     */
    public void setSpecificResourceConversions(SpecificResourceConversionsType value) {
        this.specificResourceConversions = value;
    }

}
