//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataIOCharacteristicsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataIOCharacteristicsType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}DataIOCharacteristicBaseType">
 *       &lt;attribute name="busWidth" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="transferSpeed" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="maxDevices" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="numDevices" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataIOCharacteristicsType")
public class DataIOCharacteristicsType
    extends DataIOCharacteristicBaseType
{

    @XmlAttribute(name = "busWidth")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger busWidth;
    @XmlAttribute(name = "transferSpeed")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger transferSpeed;
    @XmlAttribute(name = "maxDevices")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxDevices;
    @XmlAttribute(name = "numDevices")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numDevices;

    /**
     * Gets the value of the busWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBusWidth() {
        return busWidth;
    }

    /**
     * Sets the value of the busWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBusWidth(BigInteger value) {
        this.busWidth = value;
    }

    /**
     * Gets the value of the transferSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTransferSpeed() {
        return transferSpeed;
    }

    /**
     * Sets the value of the transferSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTransferSpeed(BigInteger value) {
        this.transferSpeed = value;
    }

    /**
     * Gets the value of the maxDevices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDevices() {
        return maxDevices;
    }

    /**
     * Sets the value of the maxDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDevices(BigInteger value) {
        this.maxDevices = value;
    }

    /**
     * Gets the value of the numDevices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumDevices() {
        return numDevices;
    }

    /**
     * Sets the value of the numDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumDevices(BigInteger value) {
        this.numDevices = value;
    }

}
