//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisplayPresentationPreferencesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisplayPresentationPreferencesType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}UserCharacteristicBaseType">
 *       &lt;sequence>
 *         &lt;element name="ColorTemperaturePreference" type="{urn:tva:mpeg21:2012}ColorPreferenceType" minOccurs="0"/>
 *         &lt;element name="BrightnessPreference" type="{urn:tva:mpeg21:2012}ColorPreferenceType" minOccurs="0"/>
 *         &lt;element name="SaturationPreference" type="{urn:tva:mpeg21:2012}ColorPreferenceType" minOccurs="0"/>
 *         &lt;element name="ContrastPreference" type="{urn:tva:mpeg21:2012}ColorPreferenceType" minOccurs="0"/>
 *         &lt;element name="StereoscopicVideoConversion" type="{urn:tva:mpeg21:2012}StereoscopicVideoConversionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisplayPresentationPreferencesType", propOrder = {
    "colorTemperaturePreference",
    "brightnessPreference",
    "saturationPreference",
    "contrastPreference",
    "stereoscopicVideoConversion"
})
public class DisplayPresentationPreferencesType
    extends UserCharacteristicBaseType
{

    @XmlElement(name = "ColorTemperaturePreference")
    protected ColorPreferenceType colorTemperaturePreference;
    @XmlElement(name = "BrightnessPreference")
    protected ColorPreferenceType brightnessPreference;
    @XmlElement(name = "SaturationPreference")
    protected ColorPreferenceType saturationPreference;
    @XmlElement(name = "ContrastPreference")
    protected ColorPreferenceType contrastPreference;
    @XmlElement(name = "StereoscopicVideoConversion")
    protected StereoscopicVideoConversionType stereoscopicVideoConversion;

    /**
     * Gets the value of the colorTemperaturePreference property.
     * 
     * @return
     *     possible object is
     *     {@link ColorPreferenceType }
     *     
     */
    public ColorPreferenceType getColorTemperaturePreference() {
        return colorTemperaturePreference;
    }

    /**
     * Sets the value of the colorTemperaturePreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorPreferenceType }
     *     
     */
    public void setColorTemperaturePreference(ColorPreferenceType value) {
        this.colorTemperaturePreference = value;
    }

    /**
     * Gets the value of the brightnessPreference property.
     * 
     * @return
     *     possible object is
     *     {@link ColorPreferenceType }
     *     
     */
    public ColorPreferenceType getBrightnessPreference() {
        return brightnessPreference;
    }

    /**
     * Sets the value of the brightnessPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorPreferenceType }
     *     
     */
    public void setBrightnessPreference(ColorPreferenceType value) {
        this.brightnessPreference = value;
    }

    /**
     * Gets the value of the saturationPreference property.
     * 
     * @return
     *     possible object is
     *     {@link ColorPreferenceType }
     *     
     */
    public ColorPreferenceType getSaturationPreference() {
        return saturationPreference;
    }

    /**
     * Sets the value of the saturationPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorPreferenceType }
     *     
     */
    public void setSaturationPreference(ColorPreferenceType value) {
        this.saturationPreference = value;
    }

    /**
     * Gets the value of the contrastPreference property.
     * 
     * @return
     *     possible object is
     *     {@link ColorPreferenceType }
     *     
     */
    public ColorPreferenceType getContrastPreference() {
        return contrastPreference;
    }

    /**
     * Sets the value of the contrastPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorPreferenceType }
     *     
     */
    public void setContrastPreference(ColorPreferenceType value) {
        this.contrastPreference = value;
    }

    /**
     * Gets the value of the stereoscopicVideoConversion property.
     * 
     * @return
     *     possible object is
     *     {@link StereoscopicVideoConversionType }
     *     
     */
    public StereoscopicVideoConversionType getStereoscopicVideoConversion() {
        return stereoscopicVideoConversion;
    }

    /**
     * Sets the value of the stereoscopicVideoConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link StereoscopicVideoConversionType }
     *     
     */
    public void setStereoscopicVideoConversion(StereoscopicVideoConversionType value) {
        this.stereoscopicVideoConversion = value;
    }

}
