//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MouseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MouseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2012}UserInteractionInputSupportBaseType">
 *       &lt;sequence>
 *         &lt;element name="Mouse" type="{urn:tva:mpeg21:2012}GenericMouseType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MouseType", propOrder = {
    "mouse"
})
public class MouseType
    extends UserInteractionInputSupportBaseType
{

    @XmlElement(name = "Mouse", required = true)
    protected GenericMouseType mouse;

    /**
     * Gets the value of the mouse property.
     * 
     * @return
     *     possible object is
     *     {@link GenericMouseType }
     *     
     */
    public GenericMouseType getMouse() {
        return mouse;
    }

    /**
     * Sets the value of the mouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericMouseType }
     *     
     */
    public void setMouse(GenericMouseType value) {
        this.mouse = value;
    }

}
