//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.edutva.edutvav1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TVAMain_QNAME = new QName("urn:tva:metadata:2012", "TVAMain");
    private final static QName _DIADescriptionUnit_QNAME = new QName("urn:tva:mpeg21:2012", "DIADescriptionUnit");
    private final static QName _SystemInformationTypeCPU_QNAME = new QName("urn:tva:metadata:extended:2012", "CPU");
    private final static QName _SystemInformationTypeRAM_QNAME = new QName("urn:tva:metadata:extended:2012", "RAM");
    private final static QName _SystemInformationTypeVirtualMachine_QNAME = new QName("urn:tva:metadata:extended:2012", "VirtualMachine");
    private final static QName _SystemInformationTypeOtherSystemSW_QNAME = new QName("urn:tva:metadata:extended:2012", "OtherSystemSW");
    private final static QName _SystemInformationTypeMiddleWare_QNAME = new QName("urn:tva:metadata:extended:2012", "MiddleWare");
    private final static QName _SystemInformationTypeSupportingOS_QNAME = new QName("urn:tva:metadata:extended:2012", "SupportingOS");
    private final static QName _TVAAgentTypePersonNameIDRef_QNAME = new QName("urn:tva:metadata:2012", "PersonNameIDRef");
    private final static QName _TVAAgentTypePersonName_QNAME = new QName("urn:tva:metadata:2012", "PersonName");
    private final static QName _TVAAgentTypeOrganizationNameIDRef_QNAME = new QName("urn:tva:metadata:2012", "OrganizationNameIDRef");
    private final static QName _TVAAgentTypeOrganizationName_QNAME = new QName("urn:tva:metadata:2012", "OrganizationName");
    private final static QName _PersonNameTypeGivenName_QNAME = new QName("urn:tva:mpeg7:2008", "GivenName");
    private final static QName _PersonNameTypeTitle_QNAME = new QName("urn:tva:mpeg7:2008", "Title");
    private final static QName _PersonNameTypeSalutation_QNAME = new QName("urn:tva:mpeg7:2008", "Salutation");
    private final static QName _PersonNameTypeLinkingName_QNAME = new QName("urn:tva:mpeg7:2008", "LinkingName");
    private final static QName _PersonNameTypeNumeration_QNAME = new QName("urn:tva:mpeg7:2008", "Numeration");
    private final static QName _PersonNameTypeFamilyName_QNAME = new QName("urn:tva:mpeg7:2008", "FamilyName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.edutva.edutvav1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AudioPresentationPreferencesType.AudibleFrequencyRange }
     * 
     */
    public AudioPresentationPreferencesType.AudibleFrequencyRange createAudioPresentationPreferencesTypeAudibleFrequencyRange() {
        return new AudioPresentationPreferencesType.AudibleFrequencyRange();
    }

    /**
     * Create an instance of {@link RMPIMBAndMType }
     * 
     */
    public RMPIMBAndMType createRMPIMBAndMType() {
        return new RMPIMBAndMType();
    }

    /**
     * Create an instance of {@link CreationPreferencesType.Location }
     * 
     */
    public CreationPreferencesType.Location createCreationPreferencesTypeLocation() {
        return new CreationPreferencesType.Location();
    }

    /**
     * Create an instance of {@link ClassificationSchemeType }
     * 
     */
    public ClassificationSchemeType createClassificationSchemeType() {
        return new ClassificationSchemeType();
    }

    /**
     * Create an instance of {@link SimultaneousRenderingType }
     * 
     */
    public SimultaneousRenderingType createSimultaneousRenderingType() {
        return new SimultaneousRenderingType();
    }

    /**
     * Create an instance of {@link DirectivityType }
     * 
     */
    public DirectivityType createDirectivityType() {
        return new DirectivityType();
    }

    /**
     * Create an instance of {@link PowerCharacteristicsType }
     * 
     */
    public PowerCharacteristicsType createPowerCharacteristicsType() {
        return new PowerCharacteristicsType();
    }

    /**
     * Create an instance of {@link CodecParameterBitRateType }
     * 
     */
    public CodecParameterBitRateType createCodecParameterBitRateType() {
        return new CodecParameterBitRateType();
    }

    /**
     * Create an instance of {@link CreditsInformationTableType }
     * 
     */
    public CreditsInformationTableType createCreditsInformationTableType() {
        return new CreditsInformationTableType();
    }

    /**
     * Create an instance of {@link UsageEnvironmentType }
     * 
     */
    public UsageEnvironmentType createUsageEnvironmentType() {
        return new UsageEnvironmentType();
    }

    /**
     * Create an instance of {@link DepictedCoordinatesType }
     * 
     */
    public DepictedCoordinatesType createDepictedCoordinatesType() {
        return new DepictedCoordinatesType();
    }

    /**
     * Create an instance of {@link StringInputType }
     * 
     */
    public StringInputType createStringInputType() {
        return new StringInputType();
    }

    /**
     * Create an instance of {@link ProgramGroupTypeType }
     * 
     */
    public ProgramGroupTypeType createProgramGroupTypeType() {
        return new ProgramGroupTypeType();
    }

    /**
     * Create an instance of {@link VisualImpairmentType.Blindness }
     * 
     */
    public VisualImpairmentType.Blindness createVisualImpairmentTypeBlindness() {
        return new VisualImpairmentType.Blindness();
    }

    /**
     * Create an instance of {@link ColorVisionDeficiencyType }
     * 
     */
    public ColorVisionDeficiencyType createColorVisionDeficiencyType() {
        return new ColorVisionDeficiencyType();
    }

    /**
     * Create an instance of {@link SegmentInformationType }
     * 
     */
    public SegmentInformationType createSegmentInformationType() {
        return new SegmentInformationType();
    }

    /**
     * Create an instance of {@link PerceptualParametersType }
     * 
     */
    public PerceptualParametersType createPerceptualParametersType() {
        return new PerceptualParametersType();
    }

    /**
     * Create an instance of {@link TerminalType }
     * 
     */
    public TerminalType createTerminalType() {
        return new TerminalType();
    }

    /**
     * Create an instance of {@link BiographicInformationType }
     * 
     */
    public BiographicInformationType createBiographicInformationType() {
        return new BiographicInformationType();
    }

    /**
     * Create an instance of {@link DerivationReasonType }
     * 
     */
    public DerivationReasonType createDerivationReasonType() {
        return new DerivationReasonType();
    }

    /**
     * Create an instance of {@link PenType }
     * 
     */
    public PenType createPenType() {
        return new PenType();
    }

    /**
     * Create an instance of {@link RelIncrTimePointType }
     * 
     */
    public RelIncrTimePointType createRelIncrTimePointType() {
        return new RelIncrTimePointType();
    }

    /**
     * Create an instance of {@link ExtendRightsType }
     * 
     */
    public ExtendRightsType createExtendRightsType() {
        return new ExtendRightsType();
    }

    /**
     * Create an instance of {@link OrganizationType.NameTerm }
     * 
     */
    public OrganizationType.NameTerm createOrganizationTypeNameTerm() {
        return new OrganizationType.NameTerm();
    }

    /**
     * Create an instance of {@link SourcePreferencesType.DisseminationLocation }
     * 
     */
    public SourcePreferencesType.DisseminationLocation createSourcePreferencesTypeDisseminationLocation() {
        return new SourcePreferencesType.DisseminationLocation();
    }

    /**
     * Create an instance of {@link PersonGroupType.NameTerm }
     * 
     */
    public PersonGroupType.NameTerm createPersonGroupTypeNameTerm() {
        return new PersonGroupType.NameTerm();
    }

    /**
     * Create an instance of {@link SummaryPreferencesType }
     * 
     */
    public SummaryPreferencesType createSummaryPreferencesType() {
        return new SummaryPreferencesType();
    }

    /**
     * Create an instance of {@link ProgramInformationTableType }
     * 
     */
    public ProgramInformationTableType createProgramInformationTableType() {
        return new ProgramInformationTableType();
    }

    /**
     * Create an instance of {@link ImpulseResponseType }
     * 
     */
    public ImpulseResponseType createImpulseResponseType() {
        return new ImpulseResponseType();
    }

    /**
     * Create an instance of {@link AwardsListType }
     * 
     */
    public AwardsListType createAwardsListType() {
        return new AwardsListType();
    }

    /**
     * Create an instance of {@link AuditoryImpairmentType }
     * 
     */
    public AuditoryImpairmentType createAuditoryImpairmentType() {
        return new AuditoryImpairmentType();
    }

    /**
     * Create an instance of {@link UserActionType.ActionTime }
     * 
     */
    public UserActionType.ActionTime createUserActionTypeActionTime() {
        return new UserActionType.ActionTime();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link SpecificResourcePrioritiesType.Object }
     * 
     */
    public SpecificResourcePrioritiesType.Object createSpecificResourcePrioritiesTypeObject() {
        return new SpecificResourcePrioritiesType.Object();
    }

    /**
     * Create an instance of {@link RMPIDescriptionType }
     * 
     */
    public RMPIDescriptionType createRMPIDescriptionType() {
        return new RMPIDescriptionType();
    }

    /**
     * Create an instance of {@link TemporalSegmentLocatorType }
     * 
     */
    public TemporalSegmentLocatorType createTemporalSegmentLocatorType() {
        return new TemporalSegmentLocatorType();
    }

    /**
     * Create an instance of {@link CaptionLanguageType }
     * 
     */
    public CaptionLanguageType createCaptionLanguageType() {
        return new CaptionLanguageType();
    }

    /**
     * Create an instance of {@link ControlledTermUseType }
     * 
     */
    public ControlledTermUseType createControlledTermUseType() {
        return new ControlledTermUseType();
    }

    /**
     * Create an instance of {@link TVAIDRefElementType }
     * 
     */
    public TVAIDRefElementType createTVAIDRefElementType() {
        return new TVAIDRefElementType();
    }

    /**
     * Create an instance of {@link StereoscopicVideoConversionType }
     * 
     */
    public StereoscopicVideoConversionType createStereoscopicVideoConversionType() {
        return new StereoscopicVideoConversionType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link UniqueIDType }
     * 
     */
    public UniqueIDType createUniqueIDType() {
        return new UniqueIDType();
    }

    /**
     * Create an instance of {@link TVATermDefinitionType.Term }
     * 
     */
    public TVATermDefinitionType.Term createTVATermDefinitionTypeTerm() {
        return new TVATermDefinitionType.Term();
    }

    /**
     * Create an instance of {@link BasicSegmentDescriptionType }
     * 
     */
    public BasicSegmentDescriptionType createBasicSegmentDescriptionType() {
        return new BasicSegmentDescriptionType();
    }

    /**
     * Create an instance of {@link TVAClassificationSchemeType }
     * 
     */
    public TVAClassificationSchemeType createTVAClassificationSchemeType() {
        return new TVAClassificationSchemeType();
    }

    /**
     * Create an instance of {@link co.com.edutva.edutvav1.TermDefinitionBaseType.Name }
     * 
     */
    public co.com.edutva.edutvav1.TermDefinitionBaseType.Name createTermDefinitionBaseTypeName() {
        return new co.com.edutva.edutvav1.TermDefinitionBaseType.Name();
    }

    /**
     * Create an instance of {@link PersonGroupType }
     * 
     */
    public PersonGroupType createPersonGroupType() {
        return new PersonGroupType();
    }

    /**
     * Create an instance of {@link CodecParameterBitRateType.BitRate }
     * 
     */
    public CodecParameterBitRateType.BitRate createCodecParameterBitRateTypeBitRate() {
        return new CodecParameterBitRateType.BitRate();
    }

    /**
     * Create an instance of {@link ErraticityType }
     * 
     */
    public ErraticityType createErraticityType() {
        return new ErraticityType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.ParentalGuidance }
     * 
     */
    public ClassificationPreferencesType.ParentalGuidance createClassificationPreferencesTypeParentalGuidance() {
        return new ClassificationPreferencesType.ParentalGuidance();
    }

    /**
     * Create an instance of {@link ColorType }
     * 
     */
    public ColorType createColorType() {
        return new ColorType();
    }

    /**
     * Create an instance of {@link ContentPropertiesType }
     * 
     */
    public ContentPropertiesType createContentPropertiesType() {
        return new ContentPropertiesType();
    }

    /**
     * Create an instance of {@link NetworkConditionType.AvailableBandwidth }
     * 
     */
    public NetworkConditionType.AvailableBandwidth createNetworkConditionTypeAvailableBandwidth() {
        return new NetworkConditionType.AvailableBandwidth();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.Genre }
     * 
     */
    public ClassificationPreferencesType.Genre createClassificationPreferencesTypeGenre() {
        return new ClassificationPreferencesType.Genre();
    }

    /**
     * Create an instance of {@link NaturalEnvironmentInformationTableType }
     * 
     */
    public NaturalEnvironmentInformationTableType createNaturalEnvironmentInformationTableType() {
        return new NaturalEnvironmentInformationTableType();
    }

    /**
     * Create an instance of {@link StoragesType }
     * 
     */
    public StoragesType createStoragesType() {
        return new StoragesType();
    }

    /**
     * Create an instance of {@link TargetingInformationType }
     * 
     */
    public TargetingInformationType createTargetingInformationType() {
        return new TargetingInformationType();
    }

    /**
     * Create an instance of {@link PersonNameFragmentType }
     * 
     */
    public PersonNameFragmentType createPersonNameFragmentType() {
        return new PersonNameFragmentType();
    }

    /**
     * Create an instance of {@link SummaryPreferencesType.SummaryType }
     * 
     */
    public SummaryPreferencesType.SummaryType createSummaryPreferencesTypeSummaryType() {
        return new SummaryPreferencesType.SummaryType();
    }

    /**
     * Create an instance of {@link NetworkType }
     * 
     */
    public NetworkType createNetworkType() {
        return new NetworkType();
    }

    /**
     * Create an instance of {@link ModalityPrioritiesType }
     * 
     */
    public ModalityPrioritiesType createModalityPrioritiesType() {
        return new ModalityPrioritiesType();
    }

    /**
     * Create an instance of {@link VideoCapabilitiesType }
     * 
     */
    public VideoCapabilitiesType createVideoCapabilitiesType() {
        return new VideoCapabilitiesType();
    }

    /**
     * Create an instance of {@link NetworkConditionType }
     * 
     */
    public NetworkConditionType createNetworkConditionType() {
        return new NetworkConditionType();
    }

    /**
     * Create an instance of {@link AccessibilityInformationType }
     * 
     */
    public AccessibilityInformationType createAccessibilityInformationType() {
        return new AccessibilityInformationType();
    }

    /**
     * Create an instance of {@link UsersType }
     * 
     */
    public UsersType createUsersType() {
        return new UsersType();
    }

    /**
     * Create an instance of {@link CreationPreferencesType.Title }
     * 
     */
    public CreationPreferencesType.Title createCreationPreferencesTypeTitle() {
        return new CreationPreferencesType.Title();
    }

    /**
     * Create an instance of {@link M21UsageHistoryType }
     * 
     */
    public M21UsageHistoryType createM21UsageHistoryType() {
        return new M21UsageHistoryType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.Subject }
     * 
     */
    public ClassificationPreferencesType.Subject createClassificationPreferencesTypeSubject() {
        return new ClassificationPreferencesType.Subject();
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType.MaterialForPrinting }
     * 
     */
    public ExtendedContentDescriptionType.MaterialForPrinting createExtendedContentDescriptionTypeMaterialForPrinting() {
        return new ExtendedContentDescriptionType.MaterialForPrinting();
    }

    /**
     * Create an instance of {@link MediaFormatType.AudioCoding.AudioChannels }
     * 
     */
    public MediaFormatType.AudioCoding.AudioChannels createMediaFormatTypeAudioCodingAudioChannels() {
        return new MediaFormatType.AudioCoding.AudioChannels();
    }

    /**
     * Create an instance of {@link BrowsingPreferencesType }
     * 
     */
    public BrowsingPreferencesType createBrowsingPreferencesType() {
        return new BrowsingPreferencesType();
    }

    /**
     * Create an instance of {@link NaturalEnvironmentInformationType }
     * 
     */
    public NaturalEnvironmentInformationType createNaturalEnvironmentInformationType() {
        return new NaturalEnvironmentInformationType();
    }

    /**
     * Create an instance of {@link GeneralResourcePrioritiesType }
     * 
     */
    public GeneralResourcePrioritiesType createGeneralResourcePrioritiesType() {
        return new GeneralResourcePrioritiesType();
    }

    /**
     * Create an instance of {@link DataIOsType }
     * 
     */
    public DataIOsType createDataIOsType() {
        return new DataIOsType();
    }

    /**
     * Create an instance of {@link PlaceType.PostalAddress }
     * 
     */
    public PlaceType.PostalAddress createPlaceTypePostalAddress() {
        return new PlaceType.PostalAddress();
    }

    /**
     * Create an instance of {@link ExtendedTVAMainType }
     * 
     */
    public ExtendedTVAMainType createExtendedTVAMainType() {
        return new ExtendedTVAMainType();
    }

    /**
     * Create an instance of {@link SynopsisType }
     * 
     */
    public SynopsisType createSynopsisType() {
        return new SynopsisType();
    }

    /**
     * Create an instance of {@link PersonType.Affiliation }
     * 
     */
    public PersonType.Affiliation createPersonTypeAffiliation() {
        return new PersonType.Affiliation();
    }

    /**
     * Create an instance of {@link ControlledTermType }
     * 
     */
    public ControlledTermType createControlledTermType() {
        return new ControlledTermType();
    }

    /**
     * Create an instance of {@link AncillaryRMPIType }
     * 
     */
    public AncillaryRMPIType createAncillaryRMPIType() {
        return new AncillaryRMPIType();
    }

    /**
     * Create an instance of {@link IlluminationCharacteristicsType.TypeOfIllumination.Chromaticity }
     * 
     */
    public IlluminationCharacteristicsType.TypeOfIllumination.Chromaticity createIlluminationCharacteristicsTypeTypeOfIlluminationChromaticity() {
        return new IlluminationCharacteristicsType.TypeOfIllumination.Chromaticity();
    }

    /**
     * Create an instance of {@link SpecificResourceConversionsType }
     * 
     */
    public SpecificResourceConversionsType createSpecificResourceConversionsType() {
        return new SpecificResourceConversionsType();
    }

    /**
     * Create an instance of {@link MediaFormatType.AudioCoding.Sample }
     * 
     */
    public MediaFormatType.AudioCoding.Sample createMediaFormatTypeAudioCodingSample() {
        return new MediaFormatType.AudioCoding.Sample();
    }

    /**
     * Create an instance of {@link GenericMouseType }
     * 
     */
    public GenericMouseType createGenericMouseType() {
        return new GenericMouseType();
    }

    /**
     * Create an instance of {@link DescriptionMetadataType }
     * 
     */
    public DescriptionMetadataType createDescriptionMetadataType() {
        return new DescriptionMetadataType();
    }

    /**
     * Create an instance of {@link MediaFormatType.BitRate }
     * 
     */
    public MediaFormatType.BitRate createMediaFormatTypeBitRate() {
        return new MediaFormatType.BitRate();
    }

    /**
     * Create an instance of {@link MediaFormatType.VisualCoding.Frame }
     * 
     */
    public MediaFormatType.VisualCoding.Frame createMediaFormatTypeVisualCodingFrame() {
        return new MediaFormatType.VisualCoding.Frame();
    }

    /**
     * Create an instance of {@link UserInformationType }
     * 
     */
    public UserInformationType createUserInformationType() {
        return new UserInformationType();
    }

    /**
     * Create an instance of {@link MediaIncrDurationType }
     * 
     */
    public MediaIncrDurationType createMediaIncrDurationType() {
        return new MediaIncrDurationType();
    }

    /**
     * Create an instance of {@link SourcePreferencesType.Disseminator }
     * 
     */
    public SourcePreferencesType.Disseminator createSourcePreferencesTypeDisseminator() {
        return new SourcePreferencesType.Disseminator();
    }

    /**
     * Create an instance of {@link ImageLocatorType }
     * 
     */
    public ImageLocatorType createImageLocatorType() {
        return new ImageLocatorType();
    }

    /**
     * Create an instance of {@link AnalogueExportRightType }
     * 
     */
    public AnalogueExportRightType createAnalogueExportRightType() {
        return new AnalogueExportRightType();
    }

    /**
     * Create an instance of {@link ProgramInformationType }
     * 
     */
    public ProgramInformationType createProgramInformationType() {
        return new ProgramInformationType();
    }

    /**
     * Create an instance of {@link AudioLanguageType }
     * 
     */
    public AudioLanguageType createAudioLanguageType() {
        return new AudioLanguageType();
    }

    /**
     * Create an instance of {@link MediaRelIncrTimePointType }
     * 
     */
    public MediaRelIncrTimePointType createMediaRelIncrTimePointType() {
        return new MediaRelIncrTimePointType();
    }

    /**
     * Create an instance of {@link AudioPresentationPreferencesType }
     * 
     */
    public AudioPresentationPreferencesType createAudioPresentationPreferencesType() {
        return new AudioPresentationPreferencesType();
    }

    /**
     * Create an instance of {@link TitleMediaType }
     * 
     */
    public TitleMediaType createTitleMediaType() {
        return new TitleMediaType();
    }

    /**
     * Create an instance of {@link UserActionListType }
     * 
     */
    public UserActionListType createUserActionListType() {
        return new UserActionListType();
    }

    /**
     * Create an instance of {@link DisplayCapabilityType }
     * 
     */
    public DisplayCapabilityType createDisplayCapabilityType() {
        return new DisplayCapabilityType();
    }

    /**
     * Create an instance of {@link CRIDRefType }
     * 
     */
    public CRIDRefType createCRIDRefType() {
        return new CRIDRefType();
    }

    /**
     * Create an instance of {@link FontType }
     * 
     */
    public FontType createFontType() {
        return new FontType();
    }

    /**
     * Create an instance of {@link IncrDurationType }
     * 
     */
    public IncrDurationType createIncrDurationType() {
        return new IncrDurationType();
    }

    /**
     * Create an instance of {@link MediaFormatType.VisualCoding.Format }
     * 
     */
    public MediaFormatType.VisualCoding.Format createMediaFormatTypeVisualCodingFormat() {
        return new MediaFormatType.VisualCoding.Format();
    }

    /**
     * Create an instance of {@link BrowsingPreferencesType.PreferenceCondition }
     * 
     */
    public BrowsingPreferencesType.PreferenceCondition createBrowsingPreferencesTypePreferenceCondition() {
        return new BrowsingPreferencesType.PreferenceCondition();
    }

    /**
     * Create an instance of {@link AudioOutputType }
     * 
     */
    public AudioOutputType createAudioOutputType() {
        return new AudioOutputType();
    }

    /**
     * Create an instance of {@link ElectronicAddressType }
     * 
     */
    public ElectronicAddressType createElectronicAddressType() {
        return new ElectronicAddressType();
    }

    /**
     * Create an instance of {@link TermNameType }
     * 
     */
    public TermNameType createTermNameType() {
        return new TermNameType();
    }

    /**
     * Create an instance of {@link StereoscopicVideoConversionType.From3DStereoscopicTo2D }
     * 
     */
    public StereoscopicVideoConversionType.From3DStereoscopicTo2D createStereoscopicVideoConversionTypeFrom3DStereoscopicTo2D() {
        return new StereoscopicVideoConversionType.From3DStereoscopicTo2D();
    }

    /**
     * Create an instance of {@link RAMType }
     * 
     */
    public RAMType createRAMType() {
        return new RAMType();
    }

    /**
     * Create an instance of {@link TextFocusOfAttentionType.Keyword }
     * 
     */
    public TextFocusOfAttentionType.Keyword createTextFocusOfAttentionTypeKeyword() {
        return new TextFocusOfAttentionType.Keyword();
    }

    /**
     * Create an instance of {@link AgeRangeType }
     * 
     */
    public AgeRangeType createAgeRangeType() {
        return new AgeRangeType();
    }

    /**
     * Create an instance of {@link DisplayType }
     * 
     */
    public DisplayType createDisplayType() {
        return new DisplayType();
    }

    /**
     * Create an instance of {@link AudioEnvironmentType }
     * 
     */
    public AudioEnvironmentType createAudioEnvironmentType() {
        return new AudioEnvironmentType();
    }

    /**
     * Create an instance of {@link AspectRatioType }
     * 
     */
    public AspectRatioType createAspectRatioType() {
        return new AspectRatioType();
    }

    /**
     * Create an instance of {@link EducationalContextAttributesType }
     * 
     */
    public EducationalContextAttributesType createEducationalContextAttributesType() {
        return new EducationalContextAttributesType();
    }

    /**
     * Create an instance of {@link DisplaysType }
     * 
     */
    public DisplaysType createDisplaysType() {
        return new DisplaysType();
    }

    /**
     * Create an instance of {@link MicrophoneType }
     * 
     */
    public MicrophoneType createMicrophoneType() {
        return new MicrophoneType();
    }

    /**
     * Create an instance of {@link MediaFormatType.VisualCoding.Pixel }
     * 
     */
    public MediaFormatType.VisualCoding.Pixel createMediaFormatTypeVisualCodingPixel() {
        return new MediaFormatType.VisualCoding.Pixel();
    }

    /**
     * Create an instance of {@link KeyInputType }
     * 
     */
    public KeyInputType createKeyInputType() {
        return new KeyInputType();
    }

    /**
     * Create an instance of {@link TermUseType }
     * 
     */
    public TermUseType createTermUseType() {
        return new TermUseType();
    }

    /**
     * Create an instance of {@link SpecificResourceConversionsType.Object }
     * 
     */
    public SpecificResourceConversionsType.Object createSpecificResourceConversionsTypeObject() {
        return new SpecificResourceConversionsType.Object();
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType }
     * 
     */
    public ExtendedContentDescriptionType createExtendedContentDescriptionType() {
        return new ExtendedContentDescriptionType();
    }

    /**
     * Create an instance of {@link DescriptionMetadataType.ClassificationSchemeAlias }
     * 
     */
    public DescriptionMetadataType.ClassificationSchemeAlias createDescriptionMetadataTypeClassificationSchemeAlias() {
        return new DescriptionMetadataType.ClassificationSchemeAlias();
    }

    /**
     * Create an instance of {@link TVAMediaRelIncrTimePointType }
     * 
     */
    public TVAMediaRelIncrTimePointType createTVAMediaRelIncrTimePointType() {
        return new TVAMediaRelIncrTimePointType();
    }

    /**
     * Create an instance of {@link DestinationType.DestinationClass }
     * 
     */
    public DestinationType.DestinationClass createDestinationTypeDestinationClass() {
        return new DestinationType.DestinationClass();
    }

    /**
     * Create an instance of {@link BitRateType }
     * 
     */
    public BitRateType createBitRateType() {
        return new BitRateType();
    }

    /**
     * Create an instance of {@link FilteringAndSearchPreferencesType }
     * 
     */
    public FilteringAndSearchPreferencesType createFilteringAndSearchPreferencesType() {
        return new FilteringAndSearchPreferencesType();
    }

    /**
     * Create an instance of {@link MetadataOriginationInformationType }
     * 
     */
    public MetadataOriginationInformationType createMetadataOriginationInformationType() {
        return new MetadataOriginationInformationType();
    }

    /**
     * Create an instance of {@link TextFocusOfAttentionType }
     * 
     */
    public TextFocusOfAttentionType createTextFocusOfAttentionType() {
        return new TextFocusOfAttentionType();
    }

    /**
     * Create an instance of {@link VisualImpairmentDegreeType }
     * 
     */
    public VisualImpairmentDegreeType createVisualImpairmentDegreeType() {
        return new VisualImpairmentDegreeType();
    }

    /**
     * Create an instance of {@link MediaFormatType.VisualCoding }
     * 
     */
    public MediaFormatType.VisualCoding createMediaFormatTypeVisualCoding() {
        return new MediaFormatType.VisualCoding();
    }

    /**
     * Create an instance of {@link InlineMediaType }
     * 
     */
    public InlineMediaType createInlineMediaType() {
        return new InlineMediaType();
    }

    /**
     * Create an instance of {@link TVATermDefinitionType }
     * 
     */
    public TVATermDefinitionType createTVATermDefinitionType() {
        return new TVATermDefinitionType();
    }

    /**
     * Create an instance of {@link GroupInformationType }
     * 
     */
    public GroupInformationType createGroupInformationType() {
        return new GroupInformationType();
    }

    /**
     * Create an instance of {@link MappingTermType }
     * 
     */
    public MappingTermType createMappingTermType() {
        return new MappingTermType();
    }

    /**
     * Create an instance of {@link SourcePreferencesType.MediaFormat }
     * 
     */
    public SourcePreferencesType.MediaFormat createSourcePreferencesTypeMediaFormat() {
        return new SourcePreferencesType.MediaFormat();
    }

    /**
     * Create an instance of {@link CreationPreferencesType.DatePeriod }
     * 
     */
    public CreationPreferencesType.DatePeriod createCreationPreferencesTypeDatePeriod() {
        return new CreationPreferencesType.DatePeriod();
    }

    /**
     * Create an instance of {@link TargetPlaceType }
     * 
     */
    public TargetPlaceType createTargetPlaceType() {
        return new TargetPlaceType();
    }

    /**
     * Create an instance of {@link AwardType }
     * 
     */
    public AwardType createAwardType() {
        return new AwardType();
    }

    /**
     * Create an instance of {@link CodecParameterVertexRateType }
     * 
     */
    public CodecParameterVertexRateType createCodecParameterVertexRateType() {
        return new CodecParameterVertexRateType();
    }

    /**
     * Create an instance of {@link RelatedMaterialType }
     * 
     */
    public RelatedMaterialType createRelatedMaterialType() {
        return new RelatedMaterialType();
    }

    /**
     * Create an instance of {@link MediaRelTimePointType }
     * 
     */
    public MediaRelTimePointType createMediaRelTimePointType() {
        return new MediaRelTimePointType();
    }

    /**
     * Create an instance of {@link OrganizationType.Name }
     * 
     */
    public OrganizationType.Name createOrganizationTypeName() {
        return new OrganizationType.Name();
    }

    /**
     * Create an instance of {@link SourcePreferencesType.DisseminationSource }
     * 
     */
    public SourcePreferencesType.DisseminationSource createSourcePreferencesTypeDisseminationSource() {
        return new SourcePreferencesType.DisseminationSource();
    }

    /**
     * Create an instance of {@link UserActionHistoryType }
     * 
     */
    public UserActionHistoryType createUserActionHistoryType() {
        return new UserActionHistoryType();
    }

    /**
     * Create an instance of {@link ImageCapabilitiesType }
     * 
     */
    public ImageCapabilitiesType createImageCapabilitiesType() {
        return new ImageCapabilitiesType();
    }

    /**
     * Create an instance of {@link TerminalsType }
     * 
     */
    public TerminalsType createTerminalsType() {
        return new TerminalsType();
    }

    /**
     * Create an instance of {@link StorageCharacteristicsType }
     * 
     */
    public StorageCharacteristicsType createStorageCharacteristicsType() {
        return new StorageCharacteristicsType();
    }

    /**
     * Create an instance of {@link EpisodeOfType }
     * 
     */
    public EpisodeOfType createEpisodeOfType() {
        return new EpisodeOfType();
    }

    /**
     * Create an instance of {@link DisplayCapabilityType.ColorPrimaries }
     * 
     */
    public DisplayCapabilityType.ColorPrimaries createDisplayCapabilityTypeColorPrimaries() {
        return new DisplayCapabilityType.ColorPrimaries();
    }

    /**
     * Create an instance of {@link HumidityType }
     * 
     */
    public HumidityType createHumidityType() {
        return new HumidityType();
    }

    /**
     * Create an instance of {@link TerminalInformationTableType }
     * 
     */
    public TerminalInformationTableType createTerminalInformationTableType() {
        return new TerminalInformationTableType();
    }

    /**
     * Create an instance of {@link NetworkConditionType.Error }
     * 
     */
    public NetworkConditionType.Error createNetworkConditionTypeError() {
        return new NetworkConditionType.Error();
    }

    /**
     * Create an instance of {@link HardwareManufacturerType }
     * 
     */
    public HardwareManufacturerType createHardwareManufacturerType() {
        return new HardwareManufacturerType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link TVAParentalGuidanceType }
     * 
     */
    public TVAParentalGuidanceType createTVAParentalGuidanceType() {
        return new TVAParentalGuidanceType();
    }

    /**
     * Create an instance of {@link AudioOutputCapabilitiesType }
     * 
     */
    public AudioOutputCapabilitiesType createAudioOutputCapabilitiesType() {
        return new AudioOutputCapabilitiesType();
    }

    /**
     * Create an instance of {@link SceneGraphCapabilitiesType }
     * 
     */
    public SceneGraphCapabilitiesType createSceneGraphCapabilitiesType() {
        return new SceneGraphCapabilitiesType();
    }

    /**
     * Create an instance of {@link TimeBaseReferenceType }
     * 
     */
    public TimeBaseReferenceType createTimeBaseReferenceType() {
        return new TimeBaseReferenceType();
    }

    /**
     * Create an instance of {@link GraphicsCapabilitiesType }
     * 
     */
    public GraphicsCapabilitiesType createGraphicsCapabilitiesType() {
        return new GraphicsCapabilitiesType();
    }

    /**
     * Create an instance of {@link MediaAgentType }
     * 
     */
    public MediaAgentType createMediaAgentType() {
        return new MediaAgentType();
    }

    /**
     * Create an instance of {@link ReleaseInformationType }
     * 
     */
    public ReleaseInformationType createReleaseInformationType() {
        return new ReleaseInformationType();
    }

    /**
     * Create an instance of {@link ParentalGuidanceType }
     * 
     */
    public ParentalGuidanceType createParentalGuidanceType() {
        return new ParentalGuidanceType();
    }

    /**
     * Create an instance of {@link TVATimeType }
     * 
     */
    public TVATimeType createTVATimeType() {
        return new TVATimeType();
    }

    /**
     * Create an instance of {@link AudioOutputsType }
     * 
     */
    public AudioOutputsType createAudioOutputsType() {
        return new AudioOutputsType();
    }

    /**
     * Create an instance of {@link CreationPreferencesType.Tool }
     * 
     */
    public CreationPreferencesType.Tool createCreationPreferencesTypeTool() {
        return new CreationPreferencesType.Tool();
    }

    /**
     * Create an instance of {@link PreferenceConditionType }
     * 
     */
    public PreferenceConditionType createPreferenceConditionType() {
        return new PreferenceConditionType();
    }

    /**
     * Create an instance of {@link ExtendedRelatedMaterialType }
     * 
     */
    public ExtendedRelatedMaterialType createExtendedRelatedMaterialType() {
        return new ExtendedRelatedMaterialType();
    }

    /**
     * Create an instance of {@link ExtendedSegmentDescriptionType }
     * 
     */
    public ExtendedSegmentDescriptionType createExtendedSegmentDescriptionType() {
        return new ExtendedSegmentDescriptionType();
    }

    /**
     * Create an instance of {@link StorageType }
     * 
     */
    public StorageType createStorageType() {
        return new StorageType();
    }

    /**
     * Create an instance of {@link FocusOfAttentionType }
     * 
     */
    public FocusOfAttentionType createFocusOfAttentionType() {
        return new FocusOfAttentionType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link AudiogramType }
     * 
     */
    public AudiogramType createAudiogramType() {
        return new AudiogramType();
    }

    /**
     * Create an instance of {@link UpdateIntervalType }
     * 
     */
    public UpdateIntervalType createUpdateIntervalType() {
        return new UpdateIntervalType();
    }

    /**
     * Create an instance of {@link co.com.edutva.edutvav1.InlineTermDefinitionType.Name }
     * 
     */
    public co.com.edutva.edutvav1.InlineTermDefinitionType.Name createInlineTermDefinitionTypeName() {
        return new co.com.edutva.edutvav1.InlineTermDefinitionType.Name();
    }

    /**
     * Create an instance of {@link ModalityPrioritiesType.Modality }
     * 
     */
    public ModalityPrioritiesType.Modality createModalityPrioritiesTypeModality() {
        return new ModalityPrioritiesType.Modality();
    }

    /**
     * Create an instance of {@link LowVisionImpairmentType }
     * 
     */
    public LowVisionImpairmentType createLowVisionImpairmentType() {
        return new LowVisionImpairmentType();
    }

    /**
     * Create an instance of {@link GroupInformationTableType }
     * 
     */
    public GroupInformationTableType createGroupInformationTableType() {
        return new GroupInformationTableType();
    }

    /**
     * Create an instance of {@link SegmentListType }
     * 
     */
    public SegmentListType createSegmentListType() {
        return new SegmentListType();
    }

    /**
     * Create an instance of {@link GenericPenType }
     * 
     */
    public GenericPenType createGenericPenType() {
        return new GenericPenType();
    }

    /**
     * Create an instance of {@link ProgramDescriptionType }
     * 
     */
    public ProgramDescriptionType createProgramDescriptionType() {
        return new ProgramDescriptionType();
    }

    /**
     * Create an instance of {@link UsagePreferencesType }
     * 
     */
    public UsagePreferencesType createUsagePreferencesType() {
        return new UsagePreferencesType();
    }

    /**
     * Create an instance of {@link TemporalSegmentLocatorType.BytePosition }
     * 
     */
    public TemporalSegmentLocatorType.BytePosition createTemporalSegmentLocatorTypeBytePosition() {
        return new TemporalSegmentLocatorType.BytePosition();
    }

    /**
     * Create an instance of {@link PresentationPriorityPreferenceType }
     * 
     */
    public PresentationPriorityPreferenceType createPresentationPriorityPreferenceType() {
        return new PresentationPriorityPreferenceType();
    }

    /**
     * Create an instance of {@link TextualType }
     * 
     */
    public TextualType createTextualType() {
        return new TextualType();
    }

    /**
     * Create an instance of {@link NetworkConditionType.Delay }
     * 
     */
    public NetworkConditionType.Delay createNetworkConditionTypeDelay() {
        return new NetworkConditionType.Delay();
    }

    /**
     * Create an instance of {@link NetworksType }
     * 
     */
    public NetworksType createNetworksType() {
        return new NetworksType();
    }

    /**
     * Create an instance of {@link ColorPreferenceType.Value }
     * 
     */
    public ColorPreferenceType.Value createColorPreferenceTypeValue() {
        return new ColorPreferenceType.Value();
    }

    /**
     * Create an instance of {@link ReleaseDateType }
     * 
     */
    public ReleaseDateType createReleaseDateType() {
        return new ReleaseDateType();
    }

    /**
     * Create an instance of {@link ResolutionType }
     * 
     */
    public ResolutionType createResolutionType() {
        return new ResolutionType();
    }

    /**
     * Create an instance of {@link CreationPreferencesType.Keyword }
     * 
     */
    public CreationPreferencesType.Keyword createCreationPreferencesTypeKeyword() {
        return new CreationPreferencesType.Keyword();
    }

    /**
     * Create an instance of {@link SegmentInformationTableType }
     * 
     */
    public SegmentInformationTableType createSegmentInformationTableType() {
        return new SegmentInformationTableType();
    }

    /**
     * Create an instance of {@link CodecParameterFillRateType }
     * 
     */
    public CodecParameterFillRateType createCodecParameterFillRateType() {
        return new CodecParameterFillRateType();
    }

    /**
     * Create an instance of {@link M21ReferenceType }
     * 
     */
    public M21ReferenceType createM21ReferenceType() {
        return new M21ReferenceType();
    }

    /**
     * Create an instance of {@link GenrePrioritiesType }
     * 
     */
    public GenrePrioritiesType createGenrePrioritiesType() {
        return new GenrePrioritiesType();
    }

    /**
     * Create an instance of {@link ExtendedLanguageType }
     * 
     */
    public ExtendedLanguageType createExtendedLanguageType() {
        return new ExtendedLanguageType();
    }

    /**
     * Create an instance of {@link IlluminationCharacteristicsType.TypeOfIllumination }
     * 
     */
    public IlluminationCharacteristicsType.TypeOfIllumination createIlluminationCharacteristicsTypeTypeOfIllumination() {
        return new IlluminationCharacteristicsType.TypeOfIllumination();
    }

    /**
     * Create an instance of {@link UsageHistoryType }
     * 
     */
    public UsageHistoryType createUsageHistoryType() {
        return new UsageHistoryType();
    }

    /**
     * Create an instance of {@link DIA }
     * 
     */
    public DIA createDIA() {
        return new DIA();
    }

    /**
     * Create an instance of {@link PlaceType.AdministrativeUnit }
     * 
     */
    public PlaceType.AdministrativeUnit createPlaceTypeAdministrativeUnit() {
        return new PlaceType.AdministrativeUnit();
    }

    /**
     * Create an instance of {@link VersionedControlledTermType }
     * 
     */
    public VersionedControlledTermType createVersionedControlledTermType() {
        return new VersionedControlledTermType();
    }

    /**
     * Create an instance of {@link AudioModeType }
     * 
     */
    public AudioModeType createAudioModeType() {
        return new AudioModeType();
    }

    /**
     * Create an instance of {@link ConversionType }
     * 
     */
    public ConversionType createConversionType() {
        return new ConversionType();
    }

    /**
     * Create an instance of {@link NaturalEnvironmentType }
     * 
     */
    public NaturalEnvironmentType createNaturalEnvironmentType() {
        return new NaturalEnvironmentType();
    }

    /**
     * Create an instance of {@link LowVisionImpairmentType.Hemianopia }
     * 
     */
    public LowVisionImpairmentType.Hemianopia createLowVisionImpairmentTypeHemianopia() {
        return new LowVisionImpairmentType.Hemianopia();
    }

    /**
     * Create an instance of {@link MediaFormatType }
     * 
     */
    public MediaFormatType createMediaFormatType() {
        return new MediaFormatType();
    }

    /**
     * Create an instance of {@link AwardsListItemType }
     * 
     */
    public AwardsListItemType createAwardsListItemType() {
        return new AwardsListItemType();
    }

    /**
     * Create an instance of {@link BenchmarkType }
     * 
     */
    public BenchmarkType createBenchmarkType() {
        return new BenchmarkType();
    }

    /**
     * Create an instance of {@link IPMPToolsType }
     * 
     */
    public IPMPToolsType createIPMPToolsType() {
        return new IPMPToolsType();
    }

    /**
     * Create an instance of {@link VisualImpairmentType }
     * 
     */
    public VisualImpairmentType createVisualImpairmentType() {
        return new VisualImpairmentType();
    }

    /**
     * Create an instance of {@link TVAPlaceType }
     * 
     */
    public TVAPlaceType createTVAPlaceType() {
        return new TVAPlaceType();
    }

    /**
     * Create an instance of {@link TVAAgentType }
     * 
     */
    public TVAAgentType createTVAAgentType() {
        return new TVAAgentType();
    }

    /**
     * Create an instance of {@link UserInfoType }
     * 
     */
    public UserInfoType createUserInfoType() {
        return new UserInfoType();
    }

    /**
     * Create an instance of {@link DisplayCapabilityType.Mode.SizeChar }
     * 
     */
    public DisplayCapabilityType.Mode.SizeChar createDisplayCapabilityTypeModeSizeChar() {
        return new DisplayCapabilityType.Mode.SizeChar();
    }

    /**
     * Create an instance of {@link ImageLocatorType.BytePosition }
     * 
     */
    public ImageLocatorType.BytePosition createImageLocatorTypeBytePosition() {
        return new ImageLocatorType.BytePosition();
    }

    /**
     * Create an instance of {@link TerminalInformationType }
     * 
     */
    public TerminalInformationType createTerminalInformationType() {
        return new TerminalInformationType();
    }

    /**
     * Create an instance of {@link DisplayCapabilityType.ColorBitDepth }
     * 
     */
    public DisplayCapabilityType.ColorBitDepth createDisplayCapabilityTypeColorBitDepth() {
        return new DisplayCapabilityType.ColorBitDepth();
    }

    /**
     * Create an instance of {@link ExplanationType }
     * 
     */
    public ExplanationType createExplanationType() {
        return new ExplanationType();
    }

    /**
     * Create an instance of {@link PlaceType }
     * 
     */
    public PlaceType createPlaceType() {
        return new PlaceType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.LanguageFormat }
     * 
     */
    public ClassificationPreferencesType.LanguageFormat createClassificationPreferencesTypeLanguageFormat() {
        return new ClassificationPreferencesType.LanguageFormat();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.Form }
     * 
     */
    public ClassificationPreferencesType.Form createClassificationPreferencesTypeForm() {
        return new ClassificationPreferencesType.Form();
    }

    /**
     * Create an instance of {@link ElectronicAddressType.Telephone }
     * 
     */
    public ElectronicAddressType.Telephone createElectronicAddressTypeTelephone() {
        return new ElectronicAddressType.Telephone();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.DatePeriod }
     * 
     */
    public ClassificationPreferencesType.DatePeriod createClassificationPreferencesTypeDatePeriod() {
        return new ClassificationPreferencesType.DatePeriod();
    }

    /**
     * Create an instance of {@link CreditsItemType }
     * 
     */
    public CreditsItemType createCreditsItemType() {
        return new CreditsItemType();
    }

    /**
     * Create an instance of {@link DisplayPresentationPreferencesType }
     * 
     */
    public DisplayPresentationPreferencesType createDisplayPresentationPreferencesType() {
        return new DisplayPresentationPreferencesType();
    }

    /**
     * Create an instance of {@link co.com.edutva.edutvav1.TVATermDefinitionBaseType.Name }
     * 
     */
    public co.com.edutva.edutvav1.TVATermDefinitionBaseType.Name createTVATermDefinitionBaseTypeName() {
        return new co.com.edutva.edutvav1.TVATermDefinitionBaseType.Name();
    }

    /**
     * Create an instance of {@link SpecificResourcePrioritiesType }
     * 
     */
    public SpecificResourcePrioritiesType createSpecificResourcePrioritiesType() {
        return new SpecificResourcePrioritiesType();
    }

    /**
     * Create an instance of {@link VideoAttributesType }
     * 
     */
    public VideoAttributesType createVideoAttributesType() {
        return new VideoAttributesType();
    }

    /**
     * Create an instance of {@link CreditsListType }
     * 
     */
    public CreditsListType createCreditsListType() {
        return new CreditsListType();
    }

    /**
     * Create an instance of {@link AVAttributesType }
     * 
     */
    public AVAttributesType createAVAttributesType() {
        return new AVAttributesType();
    }

    /**
     * Create an instance of {@link CodecCapabilitiesType }
     * 
     */
    public CodecCapabilitiesType createCodecCapabilitiesType() {
        return new CodecCapabilitiesType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link M21TimeType }
     * 
     */
    public M21TimeType createM21TimeType() {
        return new M21TimeType();
    }

    /**
     * Create an instance of {@link PersonGroupType.Name }
     * 
     */
    public PersonGroupType.Name createPersonGroupTypeName() {
        return new PersonGroupType.Name();
    }

    /**
     * Create an instance of {@link AggregationOfType }
     * 
     */
    public AggregationOfType createAggregationOfType() {
        return new AggregationOfType();
    }

    /**
     * Create an instance of {@link ChecksumType }
     * 
     */
    public ChecksumType createChecksumType() {
        return new ChecksumType();
    }

    /**
     * Create an instance of {@link ShortTitleType }
     * 
     */
    public ShortTitleType createShortTitleType() {
        return new ShortTitleType();
    }

    /**
     * Create an instance of {@link TVAMediaTimeType }
     * 
     */
    public TVAMediaTimeType createTVAMediaTimeType() {
        return new TVAMediaTimeType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link CreationPreferencesType }
     * 
     */
    public CreationPreferencesType createCreationPreferencesType() {
        return new CreationPreferencesType();
    }

    /**
     * Create an instance of {@link CodecParameterBufferSizeType }
     * 
     */
    public CodecParameterBufferSizeType createCodecParameterBufferSizeType() {
        return new CodecParameterBufferSizeType();
    }

    /**
     * Create an instance of {@link CPUType }
     * 
     */
    public CPUType createCPUType() {
        return new CPUType();
    }

    /**
     * Create an instance of {@link GenrePrioritiesType.Genre }
     * 
     */
    public GenrePrioritiesType.Genre createGenrePrioritiesTypeGenre() {
        return new GenrePrioritiesType.Genre();
    }

    /**
     * Create an instance of {@link IPMPToolsType.IPMPTool }
     * 
     */
    public IPMPToolsType.IPMPTool createIPMPToolsTypeIPMPTool() {
        return new IPMPToolsType.IPMPTool();
    }

    /**
     * Create an instance of {@link PreferenceConditionType.Time }
     * 
     */
    public PreferenceConditionType.Time createPreferenceConditionTypeTime() {
        return new PreferenceConditionType.Time();
    }

    /**
     * Create an instance of {@link GenericDerivationReasonType }
     * 
     */
    public GenericDerivationReasonType createGenericDerivationReasonType() {
        return new GenericDerivationReasonType();
    }

    /**
     * Create an instance of {@link RMPITableType }
     * 
     */
    public RMPITableType createRMPITableType() {
        return new RMPITableType();
    }

    /**
     * Create an instance of {@link MobilityCharacteristicsType }
     * 
     */
    public MobilityCharacteristicsType createMobilityCharacteristicsType() {
        return new MobilityCharacteristicsType();
    }

    /**
     * Create an instance of {@link ChromaticityType }
     * 
     */
    public ChromaticityType createChromaticityType() {
        return new ChromaticityType();
    }

    /**
     * Create an instance of {@link AnyDomainRightsType }
     * 
     */
    public AnyDomainRightsType createAnyDomainRightsType() {
        return new AnyDomainRightsType();
    }

    /**
     * Create an instance of {@link ClassificationSchemeTableType }
     * 
     */
    public ClassificationSchemeTableType createClassificationSchemeTableType() {
        return new ClassificationSchemeTableType();
    }

    /**
     * Create an instance of {@link SegmentReferenceType }
     * 
     */
    public SegmentReferenceType createSegmentReferenceType() {
        return new SegmentReferenceType();
    }

    /**
     * Create an instance of {@link SourcePreferencesType.DisseminationFormat }
     * 
     */
    public SourcePreferencesType.DisseminationFormat createSourcePreferencesTypeDisseminationFormat() {
        return new SourcePreferencesType.DisseminationFormat();
    }

    /**
     * Create an instance of {@link NaturalEnvironmentsType }
     * 
     */
    public NaturalEnvironmentsType createNaturalEnvironmentsType() {
        return new NaturalEnvironmentsType();
    }

    /**
     * Create an instance of {@link SourcePreferencesType }
     * 
     */
    public SourcePreferencesType createSourcePreferencesType() {
        return new SourcePreferencesType();
    }

    /**
     * Create an instance of {@link UserPreferencesType }
     * 
     */
    public UserPreferencesType createUserPreferencesType() {
        return new UserPreferencesType();
    }

    /**
     * Create an instance of {@link AudioAttributesType }
     * 
     */
    public AudioAttributesType createAudioAttributesType() {
        return new AudioAttributesType();
    }

    /**
     * Create an instance of {@link ClassificationSchemeAliasType }
     * 
     */
    public ClassificationSchemeAliasType createClassificationSchemeAliasType() {
        return new ClassificationSchemeAliasType();
    }

    /**
     * Create an instance of {@link CreationCoordinatesType }
     * 
     */
    public CreationCoordinatesType createCreationCoordinatesType() {
        return new CreationCoordinatesType();
    }

    /**
     * Create an instance of {@link RelTimePointType }
     * 
     */
    public RelTimePointType createRelTimePointType() {
        return new RelTimePointType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.Review }
     * 
     */
    public ClassificationPreferencesType.Review createClassificationPreferencesTypeReview() {
        return new ClassificationPreferencesType.Review();
    }

    /**
     * Create an instance of {@link UserActionType }
     * 
     */
    public UserActionType createUserActionType() {
        return new UserActionType();
    }

    /**
     * Create an instance of {@link PlaceType.GeographicPosition }
     * 
     */
    public PlaceType.GeographicPosition createPlaceTypeGeographicPosition() {
        return new PlaceType.GeographicPosition();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link MediaTimeType }
     * 
     */
    public MediaTimeType createMediaTimeType() {
        return new MediaTimeType();
    }

    /**
     * Create an instance of {@link TimeWindowType }
     * 
     */
    public TimeWindowType createTimeWindowType() {
        return new TimeWindowType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link TabletType }
     * 
     */
    public TabletType createTabletType() {
        return new TabletType();
    }

    /**
     * Create an instance of {@link RatingType.RatingScheme }
     * 
     */
    public RatingType.RatingScheme createRatingTypeRatingScheme() {
        return new RatingType.RatingScheme();
    }

    /**
     * Create an instance of {@link ColorPreferenceType }
     * 
     */
    public ColorPreferenceType createColorPreferenceType() {
        return new ColorPreferenceType();
    }

    /**
     * Create an instance of {@link SoundfieldType }
     * 
     */
    public SoundfieldType createSoundfieldType() {
        return new SoundfieldType();
    }

    /**
     * Create an instance of {@link TVAMediaLocatorType }
     * 
     */
    public TVAMediaLocatorType createTVAMediaLocatorType() {
        return new TVAMediaLocatorType();
    }

    /**
     * Create an instance of {@link ResourceConversionType }
     * 
     */
    public ResourceConversionType createResourceConversionType() {
        return new ResourceConversionType();
    }

    /**
     * Create an instance of {@link DeviceClassType }
     * 
     */
    public DeviceClassType createDeviceClassType() {
        return new DeviceClassType();
    }

    /**
     * Create an instance of {@link DigitalExportRightType }
     * 
     */
    public DigitalExportRightType createDigitalExportRightType() {
        return new DigitalExportRightType();
    }

    /**
     * Create an instance of {@link MediaFormatType.AudioCoding }
     * 
     */
    public MediaFormatType.AudioCoding createMediaFormatTypeAudioCoding() {
        return new MediaFormatType.AudioCoding();
    }

    /**
     * Create an instance of {@link DerivedFromType }
     * 
     */
    public DerivedFromType createDerivedFromType() {
        return new DerivedFromType();
    }

    /**
     * Create an instance of {@link SinglePointOfControlType }
     * 
     */
    public SinglePointOfControlType createSinglePointOfControlType() {
        return new SinglePointOfControlType();
    }

    /**
     * Create an instance of {@link MediaLocatorType }
     * 
     */
    public MediaLocatorType createMediaLocatorType() {
        return new MediaLocatorType();
    }

    /**
     * Create an instance of {@link SystemInformationType }
     * 
     */
    public SystemInformationType createSystemInformationType() {
        return new SystemInformationType();
    }

    /**
     * Create an instance of {@link BenchmarksType }
     * 
     */
    public BenchmarksType createBenchmarksType() {
        return new BenchmarksType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.CaptionLanguage }
     * 
     */
    public ClassificationPreferencesType.CaptionLanguage createClassificationPreferencesTypeCaptionLanguage() {
        return new ClassificationPreferencesType.CaptionLanguage();
    }

    /**
     * Create an instance of {@link TrackballType }
     * 
     */
    public TrackballType createTrackballType() {
        return new TrackballType();
    }

    /**
     * Create an instance of {@link ExtendedURIType }
     * 
     */
    public ExtendedURIType createExtendedURIType() {
        return new ExtendedURIType();
    }

    /**
     * Create an instance of {@link CaptioningAttributesType }
     * 
     */
    public CaptioningAttributesType createCaptioningAttributesType() {
        return new CaptioningAttributesType();
    }

    /**
     * Create an instance of {@link CreatorType }
     * 
     */
    public CreatorType createCreatorType() {
        return new CreatorType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link FilePropertiesType }
     * 
     */
    public FilePropertiesType createFilePropertiesType() {
        return new FilePropertiesType();
    }

    /**
     * Create an instance of {@link GeographicPointType }
     * 
     */
    public GeographicPointType createGeographicPointType() {
        return new GeographicPointType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.Language }
     * 
     */
    public ClassificationPreferencesType.Language createClassificationPreferencesTypeLanguage() {
        return new ClassificationPreferencesType.Language();
    }

    /**
     * Create an instance of {@link TVAMainType }
     * 
     */
    public TVAMainType createTVAMainType() {
        return new TVAMainType();
    }

    /**
     * Create an instance of {@link OrganizationNameType }
     * 
     */
    public OrganizationNameType createOrganizationNameType() {
        return new OrganizationNameType();
    }

    /**
     * Create an instance of {@link DataIOCharacteristicsType }
     * 
     */
    public DataIOCharacteristicsType createDataIOCharacteristicsType() {
        return new DataIOCharacteristicsType();
    }

    /**
     * Create an instance of {@link TransportCapabilitiesType }
     * 
     */
    public TransportCapabilitiesType createTransportCapabilitiesType() {
        return new TransportCapabilitiesType();
    }

    /**
     * Create an instance of {@link UserInteractionInputsType }
     * 
     */
    public UserInteractionInputsType createUserInteractionInputsType() {
        return new UserInteractionInputsType();
    }

    /**
     * Create an instance of {@link CreationPreferencesType.Creator }
     * 
     */
    public CreationPreferencesType.Creator createCreationPreferencesTypeCreator() {
        return new CreationPreferencesType.Creator();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link MemberOfType }
     * 
     */
    public MemberOfType createMemberOfType() {
        return new MemberOfType();
    }

    /**
     * Create an instance of {@link TermDefinitionType }
     * 
     */
    public TermDefinitionType createTermDefinitionType() {
        return new TermDefinitionType();
    }

    /**
     * Create an instance of {@link TargetingInformationTableType }
     * 
     */
    public TargetingInformationTableType createTargetingInformationTableType() {
        return new TargetingInformationTableType();
    }

    /**
     * Create an instance of {@link UserInformationTableType }
     * 
     */
    public UserInformationTableType createUserInformationTableType() {
        return new UserInformationTableType();
    }

    /**
     * Create an instance of {@link BasicContentDescriptionType }
     * 
     */
    public BasicContentDescriptionType createBasicContentDescriptionType() {
        return new BasicContentDescriptionType();
    }

    /**
     * Create an instance of {@link CodecParameterMemoryBandwidthType }
     * 
     */
    public CodecParameterMemoryBandwidthType createCodecParameterMemoryBandwidthType() {
        return new CodecParameterMemoryBandwidthType();
    }

    /**
     * Create an instance of {@link AudioCapabilitiesType }
     * 
     */
    public AudioCapabilitiesType createAudioCapabilitiesType() {
        return new AudioCapabilitiesType();
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link NameComponentType }
     * 
     */
    public NameComponentType createNameComponentType() {
        return new NameComponentType();
    }

    /**
     * Create an instance of {@link MouseType }
     * 
     */
    public MouseType createMouseType() {
        return new MouseType();
    }

    /**
     * Create an instance of {@link SourcePreferencesType.DisseminationDate }
     * 
     */
    public SourcePreferencesType.DisseminationDate createSourcePreferencesTypeDisseminationDate() {
        return new SourcePreferencesType.DisseminationDate();
    }

    /**
     * Create an instance of {@link DataIOType }
     * 
     */
    public DataIOType createDataIOType() {
        return new DataIOType();
    }

    /**
     * Create an instance of {@link IlluminationCharacteristicsType }
     * 
     */
    public IlluminationCharacteristicsType createIlluminationCharacteristicsType() {
        return new IlluminationCharacteristicsType();
    }

    /**
     * Create an instance of {@link CSAliasType }
     * 
     */
    public CSAliasType createCSAliasType() {
        return new CSAliasType();
    }

    /**
     * Create an instance of {@link UserInteractionInputType }
     * 
     */
    public UserInteractionInputType createUserInteractionInputType() {
        return new UserInteractionInputType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType }
     * 
     */
    public ClassificationPreferencesType createClassificationPreferencesType() {
        return new ClassificationPreferencesType();
    }

    /**
     * Create an instance of {@link NetworkCapabilityType }
     * 
     */
    public NetworkCapabilityType createNetworkCapabilityType() {
        return new NetworkCapabilityType();
    }

    /**
     * Create an instance of {@link SummaryPreferencesType.SummaryTheme }
     * 
     */
    public SummaryPreferencesType.SummaryTheme createSummaryPreferencesTypeSummaryTheme() {
        return new SummaryPreferencesType.SummaryTheme();
    }

    /**
     * Create an instance of {@link DestinationType }
     * 
     */
    public DestinationType createDestinationType() {
        return new DestinationType();
    }

    /**
     * Create an instance of {@link ConversionPreferenceType }
     * 
     */
    public ConversionPreferenceType createConversionPreferenceType() {
        return new ConversionPreferenceType();
    }

    /**
     * Create an instance of {@link ReceivingDomainRightsType }
     * 
     */
    public ReceivingDomainRightsType createReceivingDomainRightsType() {
        return new ReceivingDomainRightsType();
    }

    /**
     * Create an instance of {@link DisplayCapabilityType.ScreenSize }
     * 
     */
    public DisplayCapabilityType.ScreenSize createDisplayCapabilityTypeScreenSize() {
        return new DisplayCapabilityType.ScreenSize();
    }

    /**
     * Create an instance of {@link StereoscopicVideoConversionType.From2DTo3DStereoscopic }
     * 
     */
    public StereoscopicVideoConversionType.From2DTo3DStereoscopic createStereoscopicVideoConversionTypeFrom2DTo3DStereoscopic() {
        return new StereoscopicVideoConversionType.From2DTo3DStereoscopic();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link co.com.edutva.edutvav1.TVATermDefinitionBaseType.EquivalentCSTerm }
     * 
     */
    public co.com.edutva.edutvav1.TVATermDefinitionBaseType.EquivalentCSTerm createTVATermDefinitionBaseTypeEquivalentCSTerm() {
        return new co.com.edutva.edutvav1.TVATermDefinitionBaseType.EquivalentCSTerm();
    }

    /**
     * Create an instance of {@link FocusOfAttentionType.ROI }
     * 
     */
    public FocusOfAttentionType.ROI createFocusOfAttentionTypeROI() {
        return new FocusOfAttentionType.ROI();
    }

    /**
     * Create an instance of {@link ThreeDBenchmarkType }
     * 
     */
    public ThreeDBenchmarkType createThreeDBenchmarkType() {
        return new ThreeDBenchmarkType();
    }

    /**
     * Create an instance of {@link SignLanguageType }
     * 
     */
    public SignLanguageType createSignLanguageType() {
        return new SignLanguageType();
    }

    /**
     * Create an instance of {@link MetadataOriginationInformationTableType }
     * 
     */
    public MetadataOriginationInformationTableType createMetadataOriginationInformationTableType() {
        return new MetadataOriginationInformationTableType();
    }

    /**
     * Create an instance of {@link TermDefinitionType.Term }
     * 
     */
    public TermDefinitionType.Term createTermDefinitionTypeTerm() {
        return new TermDefinitionType.Term();
    }

    /**
     * Create an instance of {@link DisplayCapabilityType.Mode }
     * 
     */
    public DisplayCapabilityType.Mode createDisplayCapabilityTypeMode() {
        return new DisplayCapabilityType.Mode();
    }

    /**
     * Create an instance of {@link TVAPersonNameType }
     * 
     */
    public TVAPersonNameType createTVAPersonNameType() {
        return new TVAPersonNameType();
    }

    /**
     * Create an instance of {@link GenreType }
     * 
     */
    public GenreType createGenreType() {
        return new GenreType();
    }

    /**
     * Create an instance of {@link ClassificationPreferencesType.Country }
     * 
     */
    public ClassificationPreferencesType.Country createClassificationPreferencesTypeCountry() {
        return new ClassificationPreferencesType.Country();
    }

    /**
     * Create an instance of {@link CPUBenchmarkType }
     * 
     */
    public CPUBenchmarkType createCPUBenchmarkType() {
        return new CPUBenchmarkType();
    }

    /**
     * Create an instance of {@link GraphicsPresentationPreferencesType }
     * 
     */
    public GraphicsPresentationPreferencesType createGraphicsPresentationPreferencesType() {
        return new GraphicsPresentationPreferencesType();
    }

    /**
     * Create an instance of {@link UserIdentifierType }
     * 
     */
    public UserIdentifierType createUserIdentifierType() {
        return new UserIdentifierType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAMainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2012", name = "TVAMain")
    public JAXBElement<TVAMainType> createTVAMain(TVAMainType value) {
        return new JAXBElement<TVAMainType>(_TVAMain_QNAME, TVAMainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DIABaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg21:2012", name = "DIADescriptionUnit")
    public JAXBElement<DIABaseType> createDIADescriptionUnit(DIABaseType value) {
        return new JAXBElement<DIABaseType>(_DIADescriptionUnit_QNAME, DIABaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CPUType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2012", name = "CPU", scope = SystemInformationType.class)
    public JAXBElement<CPUType> createSystemInformationTypeCPU(CPUType value) {
        return new JAXBElement<CPUType>(_SystemInformationTypeCPU_QNAME, CPUType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RAMType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2012", name = "RAM", scope = SystemInformationType.class)
    public JAXBElement<RAMType> createSystemInformationTypeRAM(RAMType value) {
        return new JAXBElement<RAMType>(_SystemInformationTypeRAM_QNAME, RAMType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2012", name = "VirtualMachine", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeVirtualMachine(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeVirtualMachine_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2012", name = "OtherSystemSW", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeOtherSystemSW(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeOtherSystemSW_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2012", name = "MiddleWare", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeMiddleWare(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeMiddleWare_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2012", name = "SupportingOS", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeSupportingOS(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeSupportingOS_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAIDRefElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2012", name = "PersonNameIDRef", scope = TVAAgentType.class)
    public JAXBElement<TVAIDRefElementType> createTVAAgentTypePersonNameIDRef(TVAIDRefElementType value) {
        return new JAXBElement<TVAIDRefElementType>(_TVAAgentTypePersonNameIDRef_QNAME, TVAIDRefElementType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAPersonNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2012", name = "PersonName", scope = TVAAgentType.class)
    public JAXBElement<TVAPersonNameType> createTVAAgentTypePersonName(TVAPersonNameType value) {
        return new JAXBElement<TVAPersonNameType>(_TVAAgentTypePersonName_QNAME, TVAPersonNameType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAIDRefElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2012", name = "OrganizationNameIDRef", scope = TVAAgentType.class)
    public JAXBElement<TVAIDRefElementType> createTVAAgentTypeOrganizationNameIDRef(TVAIDRefElementType value) {
        return new JAXBElement<TVAIDRefElementType>(_TVAAgentTypeOrganizationNameIDRef_QNAME, TVAIDRefElementType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextualType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2012", name = "OrganizationName", scope = TVAAgentType.class)
    public JAXBElement<TextualType> createTVAAgentTypeOrganizationName(TextualType value) {
        return new JAXBElement<TextualType>(_TVAAgentTypeOrganizationName_QNAME, TextualType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg7:2008", name = "GivenName", scope = PersonNameType.class)
    public JAXBElement<NameComponentType> createPersonNameTypeGivenName(NameComponentType value) {
        return new JAXBElement<NameComponentType>(_PersonNameTypeGivenName_QNAME, NameComponentType.class, PersonNameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg7:2008", name = "Title", scope = PersonNameType.class)
    public JAXBElement<NameComponentType> createPersonNameTypeTitle(NameComponentType value) {
        return new JAXBElement<NameComponentType>(_PersonNameTypeTitle_QNAME, NameComponentType.class, PersonNameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg7:2008", name = "Salutation", scope = PersonNameType.class)
    public JAXBElement<NameComponentType> createPersonNameTypeSalutation(NameComponentType value) {
        return new JAXBElement<NameComponentType>(_PersonNameTypeSalutation_QNAME, NameComponentType.class, PersonNameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg7:2008", name = "LinkingName", scope = PersonNameType.class)
    public JAXBElement<NameComponentType> createPersonNameTypeLinkingName(NameComponentType value) {
        return new JAXBElement<NameComponentType>(_PersonNameTypeLinkingName_QNAME, NameComponentType.class, PersonNameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg7:2008", name = "Numeration", scope = PersonNameType.class)
    public JAXBElement<String> createPersonNameTypeNumeration(String value) {
        return new JAXBElement<String>(_PersonNameTypeNumeration_QNAME, String.class, PersonNameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:mpeg7:2008", name = "FamilyName", scope = PersonNameType.class)
    public JAXBElement<NameComponentType> createPersonNameTypeFamilyName(NameComponentType value) {
        return new JAXBElement<NameComponentType>(_PersonNameTypeFamilyName_QNAME, NameComponentType.class, PersonNameType.class, value);
    }

}
