//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:tva:mpeg21:2012", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.edutva.edutvav1;
