//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 06:14:38 PM COT 
//


package co.com.edutva.edutvav1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeBaseReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeBaseReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MediaTimePoint" type="{urn:tva:mpeg7:2008}mediaTimePointType"/>
 *           &lt;element name="MediaRelIncrTimePoint" type="{urn:tva:mpeg7:2008}MediaRelIncrTimePointType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="timebaseId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeBaseReferenceType", namespace = "urn:tva:metadata:2012", propOrder = {
    "mediaTimePoint",
    "mediaRelIncrTimePoint"
})
public class TimeBaseReferenceType {

    @XmlElement(name = "MediaTimePoint")
    protected String mediaTimePoint;
    @XmlElement(name = "MediaRelIncrTimePoint")
    protected MediaRelIncrTimePointType mediaRelIncrTimePoint;
    @XmlAttribute(name = "timebaseId")
    protected String timebaseId;

    /**
     * Gets the value of the mediaTimePoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaTimePoint() {
        return mediaTimePoint;
    }

    /**
     * Sets the value of the mediaTimePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaTimePoint(String value) {
        this.mediaTimePoint = value;
    }

    /**
     * Gets the value of the mediaRelIncrTimePoint property.
     * 
     * @return
     *     possible object is
     *     {@link MediaRelIncrTimePointType }
     *     
     */
    public MediaRelIncrTimePointType getMediaRelIncrTimePoint() {
        return mediaRelIncrTimePoint;
    }

    /**
     * Sets the value of the mediaRelIncrTimePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaRelIncrTimePointType }
     *     
     */
    public void setMediaRelIncrTimePoint(MediaRelIncrTimePointType value) {
        this.mediaRelIncrTimePoint = value;
    }

    /**
     * Gets the value of the timebaseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimebaseId() {
        return timebaseId;
    }

    /**
     * Sets the value of the timebaseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimebaseId(String value) {
        this.timebaseId = value;
    }

}
